-- MySQL Script generated by MySQL Workbench
-- sáb 09 abr 2016 11:39:00 COT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_sensor
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_sensor` ;

-- -----------------------------------------------------
-- Schema bd_sensor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_sensor` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bd_sensor` ;

-- -----------------------------------------------------
-- Table `bd_sensor`.`TipoSensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_sensor`.`TipoSensor` ;

CREATE TABLE IF NOT EXISTS `bd_sensor`.`TipoSensor` (
  `idTipoSensor` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `NombreTipoSensor` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idTipoSensor`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sensor`.`Sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_sensor`.`Sensor` ;

CREATE TABLE IF NOT EXISTS `bd_sensor`.`Sensor` (
  `idSensor` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `NombreSensor` VARCHAR(45) NOT NULL COMMENT '',
  `Referencia` VARCHAR(45) NULL COMMENT '',
  `Descripcion` VARCHAR(100) NULL COMMENT '',
  `insertDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `updateDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `Maximo` FLOAT NULL COMMENT '',
  `Minimo` FLOAT NULL COMMENT '',
  `Altura` FLOAT NULL COMMENT '',
  `fk_idTipoSensor` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idSensor`, `fk_idTipoSensor`)  COMMENT '',
  INDEX `fk_Sensor_TipoSensor1_idx` (`fk_idTipoSensor` ASC)  COMMENT '',
  CONSTRAINT `fk_Sensor_TipoSensor1`
    FOREIGN KEY (`fk_idTipoSensor`)
    REFERENCES `bd_sensor`.`TipoSensor` (`idTipoSensor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sensor`.`Dato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_sensor`.`Dato` ;

CREATE TABLE IF NOT EXISTS `bd_sensor`.`Dato` (
  `idDato` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `Dato` VARCHAR(45) NOT NULL COMMENT '',
  `insertDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `updateDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `fk_idSensor` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idDato`)  COMMENT '',
  CONSTRAINT `fk_Dato_Sensor`
    FOREIGN KEY (`fk_idSensor`)
    REFERENCES `bd_sensor`.`Sensor` (`idSensor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
